# Generated by Django 4.0.3 on 2022-05-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('photo', models.ImageField(null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='img')),
                ('sits', models.CharField(max_length=1)),
                ('created', models.CharField(max_length=4)),
                ('engine_name', models.CharField(max_length=25)),
                ('engine_volume', models.CharField(max_length=25)),
                ('pover', models.CharField(max_length=25)),
                ('moment', models.CharField(max_length=25)),
                ('about', models.TextField(max_length=5000)),
                ('little_more_title', models.TextField(blank=True, max_length=100, null=True)),
                ('little_more', models.TextField(blank=True, max_length=1500, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdm.body')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdm.brand')),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdm.author')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdm.car')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comment',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdm.drivetype'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdm.transmission'),
        ),
    ]
