# Generated by Django 4.0.3 on 2022-05-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Car'},
        ),
    ]
